name: Generate and Push Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Generate Docs
        run: yarn gendocs

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Clone Tcukawi/Docs repository
        run: |
          git clone https://github.com/MoonLGH/Tcukawi-API.git
          rm -rf Tcukawi-API/docs
          cp -r docs/. Tcukawi-API/docs
          cd Tcukawi-API/docs
          git add .
          git commit -m "Update docs"
          git push origin main
