name: Generate and Push Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Generate Docs
        run: yarn gendocs

      - name: Make script executeable
        run: |
          chmod +x ./.github/scripts/commit.sh
          
      - name: Execute script to push docs
        run: |
          ./.github/scripts/commit.sh
